import mongoose from "mongoose";

const ProfileSchema = new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true,
        unique:true,
    },
    name:{
        type:String,
        required:true,
    },
    Bio:{
        type:String,
        required:true,
    },
    skills:[{
        type:String,
        enum:[
             "HTML",
             "CSS",
             "Tailwind CSS",
             "Bootstrap",
             "React",
             "Next.js",
             "Vue.js",
             "Angular",
             "Redux",
             "Node.js",
            "Express.js",
            "Django",
            "Flask",
            "Spring Boot",
            "ASP.NET",
            "FastAPI",
            "NestJS",
            "MongoDB",
            "MySQL",
            "PostgreSQL",
            "SQLite",
            "Redis",
            "Firebase",
            "Supabase",
            "TensorFlow",
            "PyTorch",
            "Scikit-Learn",
            "OpenCV",
            "LangChain",
            "Hugging Face",
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Jenkins",
            "GitHub Actions",
            "Linux",
            "Nginx",
            "React Native",
            "Flutter",
            "Android Studio",
            "SwiftUI",
            "Kotlin",
            "Pandas",
            "NumPy",
            "Matplotlib",
            "Seaborn",
            "Jupyter",
            "Power BI",
            "Tableau",
            "Kali Linux",
            "Burp Suite",
            "Wireshark",
            "Metasploit",
            "Git",
            "GitHub",
            "GitLab",
            "Figma",
            "Adobe XD",
            "Canva"
            ]
    }],
    skillevel:{
        type:String,
        enum:["Beginner","Intermediate","Advanced"],
        default:"Beginner",
    },
    github_link:{
        type:String,
        required:true,
    },
    photo:{
        url:String,
        public_id:String,
    },
    domains:[{
        type:String,
        enum: [
            "CLI Tools",
            "Web Frameworks",
            "Mobile Development",
            "AI/ML",
            "Backend Development",
            "Frontend Development",
            "DevOps",
            "Blockchain",
            "Data Science",
            "Cybersecurity",
            "Research",
            "Game Development",
            "IoT",
            "Computer Vision",
            "Natural Language Processing",
            "Full Stack",
            "Others",
        ],
        trim:true
    }],
    friends:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        
    }],
});
ProfileSchema.index({domains:1});
ProfileSchema.index({skills:1});
ProfileSchema.index({skillevel:1});
ProfileSchema.index({domains:1,skillevel:1});
const Profile = mongoose.model("Profile", ProfileSchema);
export default Profile;